/manipulator_systems/message_transforms:
  ros__parameters:

    incoming_topics:
      - /model/uvms/odometry

    transforms:
      /model/uvms/odometry:
        outgoing_topic: /adaptive_integral_terminal_sliding_mode_controller/system_state
        message_type: nav_msgs/msg/Odometry
        frame_id: map_fsd
        child_frame_id: base_link_fsd
