controller_manager:
  ros__parameters:
    update_rate: 100 # Hz

    adaptive_integral_terminal_sliding_mode_controller:
      type: velocity_controllers/AdaptiveIntegralTerminalSlidingModeController

    thruster_allocation_matrix_controller:
      type: thruster_allocation_matrix_controller/ThrusterAllocationMatrixController

    thruster1_controller:
      type: thruster_controllers/GazeboPassthroughController

    thruster2_controller:
      type: thruster_controllers/GazeboPassthroughController

    thruster3_controller:
      type: thruster_controllers/GazeboPassthroughController

    thruster4_controller:
      type: thruster_controllers/GazeboPassthroughController

    thruster5_controller:
      type: thruster_controllers/GazeboPassthroughController

    thruster6_controller:
      type: thruster_controllers/GazeboPassthroughController

    thruster7_controller:
      type: thruster_controllers/GazeboPassthroughController

    thruster8_controller:
      type: thruster_controllers/GazeboPassthroughController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    tcp_position_controller:
      type: forward_command_controller/ForwardCommandController

    whole_body_controller:
      type: whole_body_controllers/IKController


whole_body_controller:
  ros__parameters:
    ik_solver: task_priority_solver
    vehicle_reference_controller: adaptive_integral_terminal_sliding_mode_controller
    use_external_measured_vehicle_states: true
    manipulator_joints:
      # - alpha_axis_a # we don't need the end effector joint to be controlled
      - alpha_axis_b
      - alpha_axis_c
      - alpha_axis_d
      - alpha_axis_e
    locked_joints:
      - alpha_rs1_130_joint
      - alpha_rs1_139_joint
      - alpha_axis_a
      - thruster1_joint
      - thruster2_joint
      - thruster3_joint
      - thruster4_joint
      - thruster5_joint
      - thruster6_joint
      - thruster7_joint
      - thruster8_joint
    task_priority_solver:
      end_effector_frame_id: alpha_tcp
      constrained_joints:
        - alpha_axis_d
        - alpha_axis_e
      end_effector_pose_task:
        gain: 0.3
      joint_limit_task:
        alpha_axis_d:
          safety_tolerance: 0.78539816
          activation_threshold: 0.087
          gain: 0.2
        alpha_axis_e:
          safety_tolerance: 0.78539816
          activation_threshold: 0.087
          gain: 0.2

adaptive_integral_terminal_sliding_mode_controller:
  ros__parameters:
    reference_controller: thruster_allocation_matrix_controller
    vehicle_frame_id: "base_link_fsd"
    odom_frame_id: "map_ned"
    use_external_measured_states: true
    gains:
      lambda: 0.3
      x:
        alpha: 12.0
        k1_min: 0.1
        k2: 0.4
        k_theta: 2.0
        mu: 0.01
      y:
        alpha: 12.0
        k1_min: 0.1
        k2: 0.4
        k_theta: 2.0
        mu: 0.01
      z:
        alpha: 16.0
        k1_min: 0.1
        k2: 0.4
        k_theta: 2.0
        mu: 0.01
      rx:
        alpha: 0.5
        k1_min: 0.1
        k2: 0.4
        k_theta: 2.0
        mu: 0.01
      ry:
        alpha: 20.0
        k1_min: 0.1
        k2: 1.0
        k_theta: 2.0
        mu: 0.01
      rz:
        alpha: 14.0
        k1_min: 0.1
        k2: 0.4
        k_theta: 2.0
        mu: 0.01

thruster_allocation_matrix_controller:
  ros__parameters:
    thrusters:
      - thruster1_joint
      - thruster2_joint
      - thruster3_joint
      - thruster4_joint
      - thruster5_joint
      - thruster6_joint
      - thruster7_joint
      - thruster8_joint
    reference_controllers:
      - thruster1_controller
      - thruster2_controller
      - thruster3_controller
      - thruster4_controller
      - thruster5_controller
      - thruster6_controller
      - thruster7_controller
      - thruster8_controller
    tam:
      x:  [ -0.707,  -0.707,   0.707,  0.707,      0.0,     0.0,      0.0,     0.0]
      y:  [ 0.707,   -0.707,   0.707, -0.707,      0.0,     0.0,      0.0,     0.0]
      z:  [    0.0,     0.0,     0.0,    0.0,      1.0,     1.0,      1.0,     1.0]
      rx: [    0.0,     0.0,     0.0,    0.0, -0.21805, 0.21805, -0.21805, 0.21805]
      ry: [    0.0,     0.0,     0.0,    0.0,    -0.12,   -0.12,     0.12,    0.12]
      rz: [0.1888,  -0.1888, -0.1888, 0.1888,      0.0,     0.0,      0.0,     0.0]

thruster1_controller:
  ros__parameters:
    thruster: thruster1_joint
    topic: /model/uvms/joint/thruster1_joint/cmd_thrust

thruster2_controller:
  ros__parameters:
    thruster: thruster2_joint
    topic: /model/uvms/joint/thruster2_joint/cmd_thrust

thruster3_controller:
  ros__parameters:
    thruster: thruster3_joint
    topic: /model/uvms/joint/thruster3_joint/cmd_thrust

thruster4_controller:
  ros__parameters:
    thruster: thruster4_joint
    topic: /model/uvms/joint/thruster4_joint/cmd_thrust

thruster5_controller:
  ros__parameters:
    thruster: thruster5_joint
    topic: /model/uvms/joint/thruster5_joint/cmd_thrust

thruster6_controller:
  ros__parameters:
    thruster: thruster6_joint
    topic: /model/uvms/joint/thruster6_joint/cmd_thrust

thruster7_controller:
  ros__parameters:
    thruster: thruster7_joint
    topic: /model/uvms/joint/thruster7_joint/cmd_thrust

thruster8_controller:
  ros__parameters:
    thruster: thruster8_joint
    topic: /model/uvms/joint/thruster8_joint/cmd_thrust

tcp_position_controller:
  ros__parameters:
    joints:
      - alpha_axis_a
    interface_name: position
