controller_manager:
  ros__parameters:
    update_rate: 100 # Hz

    adaptive_integral_terminal_sliding_mode_controller:
      type: velocity_controllers/AdaptiveIntegralTerminalSlidingModeController

    thruster_allocation_matrix_controller:
      type: thruster_allocation_matrix_controller/ThrusterAllocationMatrixController

    thruster1_controller:
      type: thruster_controllers/RotationRateController

    thruster2_controller:
      type: thruster_controllers/RotationRateController

    thruster3_controller:
      type: thruster_controllers/RotationRateController

    thruster4_controller:
      type: thruster_controllers/RotationRateController

    thruster5_controller:
      type: thruster_controllers/RotationRateController

    thruster6_controller:
      type: thruster_controllers/RotationRateController

    thruster7_controller:
      type: thruster_controllers/RotationRateController

    thruster8_controller:
      type: thruster_controllers/RotationRateController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    arm_velocity_controller:
      type: forward_command_controller/ForwardCommandController

    tcp_position_controller:
      type: forward_command_controller/ForwardCommandController

adaptive_integral_terminal_sliding_mode_controller:
  ros__parameters:
    reference_controller: thruster_allocation_matrix_controller
    vehicle_frame_id: "base_link_fsd"
    odom_frame_id: "map_ned"
    gains:
      lambda: 200.0
      x:
        alpha: 10.0
        k1_min: 0.1
        k2: 10.0
        k_theta: 10.0
        mu: 1.0
      y:
        alpha: 10.0
        k1_min: 0.1
        k2: 10.0
        k_theta: 10.0
        mu: 1.0
      z:
        alpha: 12.0
        k1_min: 0.1
        k2: 15.0
        k_theta: 10.0
        mu: 1.0
      rx:
        alpha: 0.5
        k1_min: 0.1
        k2: 0.5
        k_theta: 2.0
        mu: 1.0
      ry:
        alpha: 6.0
        k1_min: 0.1
        k2: 10.0
        k_theta: 10.0
        mu: 1.0
      rz:
        alpha: 10.0
        k1_min: 0.1
        k2: 10.0
        k_theta: 10.0
        mu: 1.0

thruster_allocation_matrix_controller:
  ros__parameters:
    thrusters:
      - thruster1_joint
      - thruster2_joint
      - thruster3_joint
      - thruster4_joint
      - thruster5_joint
      - thruster6_joint
      - thruster7_joint
      - thruster8_joint
    reference_controllers:
      - thruster1_controller
      - thruster2_controller
      - thruster3_controller
      - thruster4_controller
      - thruster5_controller
      - thruster6_controller
      - thruster7_controller
      - thruster8_controller
    tam:
      x:  [ -0.707,  -0.707,   0.707,  0.707,      0.0,     0.0,      0.0,     0.0]
      y:  [ 0.707,   -0.707,   0.707, -0.707,      0.0,     0.0,      0.0,     0.0]
      z:  [    0.0,     0.0,     0.0,    0.0,      1.0,     1.0,      1.0,     1.0]
      rx: [    0.0,     0.0,     0.0,    0.0, -0.21805, 0.21805, -0.21805, 0.21805]
      ry: [    0.0,     0.0,     0.0,    0.0,    -0.12,   -0.12,     0.12,    0.12]
      rz: [0.1888,  -0.1888, -0.1888, 0.1888,      0.0,     0.0,      0.0,     0.0]

thruster1_controller:
  ros__parameters:
    thruster: thruster1_joint
    min_thrust: -40.0
    max_thrust: 60.0
    thrust_coefficient: 0.02
    propeller_diameter: 0.1
    fluid_density: 998.0

thruster2_controller:
  ros__parameters:
    thruster: thruster2_joint
    min_thrust: -40.0
    max_thrust: 60.0
    thrust_coefficient: 0.02
    propeller_diameter: 0.1
    fluid_density: 998.0

thruster3_controller:
  ros__parameters:
    thruster: thruster3_joint
    min_thrust: -40.0
    max_thrust: 60.0
    thrust_coefficient: -0.02
    propeller_diameter: 0.1
    fluid_density: 998.0

thruster4_controller:
  ros__parameters:
    thruster: thruster4_joint
    min_thrust: -40.0
    max_thrust: 60.0
    thrust_coefficient: -0.02
    propeller_diameter: 0.1
    fluid_density: 998.0

thruster5_controller:
  ros__parameters:
    thruster: thruster5_joint
    min_thrust: -40.0
    max_thrust: 60.0
    thrust_coefficient: 0.02
    propeller_diameter: 0.1
    fluid_density: 998.0

thruster6_controller:
  ros__parameters:
    thruster: thruster6_joint
    min_thrust: -40.0
    max_thrust: 60.0
    thrust_coefficient: -0.02
    propeller_diameter: 0.1
    fluid_density: 998.0

thruster7_controller:
  ros__parameters:
    thruster: thruster7_joint
    min_thrust: -40.0
    max_thrust: 60.0
    thrust_coefficient: -0.02
    propeller_diameter: 0.1
    fluid_density: 998.0

thruster8_controller:
  ros__parameters:
    thruster: thruster8_joint
    min_thrust: -40.0
    max_thrust: 60.0
    thrust_coefficient: 0.02
    propeller_diameter: 0.1
    fluid_density: 998.0

arm_velocity_controller:
  ros__parameters:
    joints:
      - alpha_axis_b
      - alpha_axis_c
      - alpha_axis_d
      - alpha_axis_e
    interface_name: velocity

tcp_position_controller:
  ros__parameters:
    joints:
      - alpha_axis_a
    interface_name: position
