pull_request_rules:
  - name: backport to iron at reviewers discretion
    conditions:
      - base=main
      - "label=backport-iron"
    actions:
      backport:
        branches:
          - iron

  - name: backport to humble at reviewers discretion
    conditions:
      - base=main
      - "label=backport-humble"
    actions:
      backport:
        branches:
          - humble

  - name: ask to resolve conflict
    conditions:
      - conflict
      - author!=mergify[bot]
    actions:
        comment:
          message: This pull request is in conflict. Could you fix it @{{author}}?

  - name: development targets main branch
    conditions:
      - base!=main
      - author!=mergify[bot]
    actions:
        comment:
          message: |
            Please target the `main` branch for development, we will backport the changes to {{base}} for you if approved and if they don't break API.
