version: "3"
services:
  blue:
    image: ghcr.io/robotic-decision-making-lab/blue:humble-desktop-nvidia
    environment:
      - DISPLAY=${DISPLAY}
      - XDG_RUNTIME_DIR=${XDG_RUNTIME_DIR}
      - LIBGL_ALWAYS_SOFTWARE=1
      - QT_X11_NO_MITSHM=1
      - WAYLAND_DISPLAY=${WAYLAND_DISPLAY} # Can be commented out if not used
      - PULSE_SERVER=${PULSE_SERVER} # Can be commented out if not used
    network_mode: host
    privileged: true
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    volumes:
      - /dev:/dev
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /mnt/wslg:/mnt/wslg
    command: tail -f /dev/null
