/control_integration/message_transforms:
  ros__parameters:

    incoming_topics:
      - /model/bluerov2/odometry

    transforms:
      /model/bluerov2/odometry:
        outgoing_topic: /model/bluerov2/odometry_fsd
        message_type: nav_msgs/msg/Odometry

        frame_id: map_fsd
        child_frame_id: base_link_fsd
