name: Check Documentation

on:
  push:
    branches:
<<<<<<< HEAD
      - jazzy
=======
      - main
>>>>>>> 992b51b (Update and remove stale project configurations (#256))
  pull_request:
    paths:
      - docs/**
  workflow_dispatch:

jobs:
  build-docs:
    name: Build documentation
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup npm
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: docs/package-lock.json

      - name: Install dependencies
        run: npm ci
        working-directory: ./docs

      - name: Build website
        run: npm run build
        working-directory: ./docs
