name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
      - 33-feature-ros2-control
  pull_request:
    paths:
      - docs/**
  workflow_dispatch:

env:
  PUSH: ${{ (github.event_name != 'pull_request') && (github.repository == 'Robotic-Decision-Making-Lab/blue') }}

jobs:
  docs:
    name: Build and deploy documentation
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup npm
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: docs/package-lock.json

      - name: Install dependencies
        run: npm ci
        working-directory: ./docs

      - name: Build website
        run: npm run build
        working-directory: ./docs

      - name: Upload build artifact
        if: env.PUSH == 'true'
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/build

      - name: Deploy to GitHub Pages
        if: env.PUSH == 'true'
        uses: actions/deploy-pages@v4
